### ISSUE TITLE
target pattern contains no `%' Error

### ISSUE THREAD

**Issue by FlyCatdev** [xiaomi-sm8450-kernel/manifest#1]
Hello! Very Thank your works, but when i near complete this error will occur ,Hope you can provide some help,Thanks

i using Ubuntu 22.04 build

INSTALL net/qrtr/qrtr.ko 
INSTALL sound/usb/snd-usb-audio-qmi.ko
DEPMOD 5.10.43-gki-g21035f5aafbb ========================================================
Building external modules and 
installing them into staging directory
+ make -C ../vendor/qcom/opensource/mmrm-driver M=/home/serv03/kernel/out/msm-kernel-cupid/host/bin:/home/serv03/kernel/kernel_platform/build/build-tools/path/linux-x86:/home/serv03/kernel/kernel_platform/tools/libufdt/utils/src:/home/serv03/kernel/kernel_platform/prebuilts-master/clang/host/linux-x86/clang-r416183b/bin:/home/serv03/kernel/kernel_platform/prebuilts/gas/linux-x86:/home/serv03/kernel/out/msm-kernel-cupid/msm-kernel/host_tools:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/home/serv03/kernel/out/msm-kernel-cupid/host/bin:/home/serv03/kernel/kernel_platform/build/build-tools/path/linux-x86:/home/serv03/kernel/kernel_platform/tools/libufdt/utils/src:/home/serv03/kernel/kernel_platform/prebuilts-master/clang/host/linux-x86/clang-r416183b/bin:/home/serv03/kernel/kernel_platform/prebuilts/gas/linux-x86:/home/serv03/kernel/out/msm-kernel-cupid/msm-kernel/host_tools:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:../../vendor/qcom/opensource/mmrm-driver KERNEL_SRC=/home/serv03/kernel/kernel_platform/./msm-kernel O=/home/serv03/kernel/out/msm-kernel-cupid/msm-kernel LLVM=1 LLVM_IAS=1 DEPMOD=depmod DTC=dtc KBUILD_MIXED_TREE=/home/serv03/kernel/out/msm-kernel-cupid/gki_kernel/dist
make: Entering directory '/home/serv03/kernel/vendor/qcom/opensource/mmrm-driver'
make -C /home/serv03/kernel/kernel_platform/./msm-kernel M=/home/serv03/kernel/out/msm-kernel-cupid/host/bin:/home/serv03/kernel/kernel_platform/build/build-tools/path/linux-x86:/home/serv03/kernel/kernel_platform/tools/libufdt/utils/src:/home/serv03/kernel/kernel_platform/prebuilts-master/clang/host/linux-x86/clang-r416183b/bin:/home/serv03/kernel/kernel_platform/prebuilts/gas/linux-x86:/home/serv03/kernel/out/msm-kernel-cupid/msm-kernel/host_tools:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/home/serv03/kernel/out/msm-kernel-cupid/host/bin:/home/serv03/kernel/kernel_platform/build/build-tools/path/linux-x86:/home/serv03/kernel/kernel_platform/tools/libufdt/utils/src:/home/serv03/kernel/kernel_platform/prebuilts-master/clang/host/linux-x86/clang-r416183b/bin:/home/serv03/kernel/kernel_platform/prebuilts/gas/linux-x86:/home/serv03/kernel/out/msm-kernel-cupid/msm-kernel/host_tools:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:../../vendor/qcom/opensource/mmrm-driver modules MMRM_ROOT=/home/serv03/kernel/kernel_platform/./msm-kernel//home/serv03/kernel/out/msm-kernel-cupid/host/bin:/home/serv03/kernel/kernel_platform/build/build-tools/path/linux-x86:/home/serv03/kernel/kernel_platform/tools/libufdt/utils/src:/home/serv03/kernel/kernel_platform/prebuilts-master/clang/host/linux-x86/clang-r416183b/bin:/home/serv03/kernel/kernel_platform/prebuilts/gas/linux-x86:/home/serv03/kernel/out/msm-kernel-cupid/msm-kernel/host_tools:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/home/serv03/kernel/out/msm-kernel-cupid/host/bin:/home/serv03/kernel/kernel_platform/build/build-tools/path/linux-x86:/home/serv03/kernel/kernel_platform/tools/libufdt/utils/src:/home/serv03/kernel/kernel_platform/prebuilts-master/clang/host/linux-x86/clang-r416183b/bin:/home/serv03/kernel/kernel_platform/prebuilts/gas/linux-x86:/home/serv03/kernel/out/msm-kernel-cupid/msm-kernel/host_tools:/usr/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:../../vendor/qcom/opensource/mmrm-driver BOARD_PLATFORM=cupid
make[1]: Entering directory '/home/serv03/kernel/kernel_platform/msm-kernel'
make[2]: Entering directory /home/serv03/kernel/out/msm-kernel-cupid/msm-kernel
/home/serv03/kernel/kernel_platform/msm-kernel/Makefile:1832: *** target pattern contains no `%`
make[2]: leaveing directory /home/serv03/kernel/out/msm-kernel-cupid/msm-kernel
Makefile:185: recipe for target '__sub-make' failed
make[1]: *** [__sub-make] Error 2 make[1]: Leaving directory '/home/serv03/kernel/kernel_platform/msm-kernel'
Makefile:7: recipe for target 'modules' failed
make: *** [modules] Error 2
make: Leaving directory '/home/serv03/kernel/vendor/qcom/opensource/mmrm-driver'

**Comment by FlyCatdev** [comment]
sorry, it seems my file is incomplete ,i try again clone it's work!

**Comment by pencc** [comment]
@FlyCatdev hi, can you boot this kernel in mi12 ?
