### ISSUE TITLE
How to pack boot.img by this kernel

### ISSUE THREAD

**Issue by pencc** [xiaomi-sm8450-kernel/manifest#2]
Hi, thanks for your work in sm8450. I try to pack Image into boot.img by /data/adb/magisk/magiskboot in Mi12. But the changed boot.img  fail to boot Mi12, it's to fashboot cycle. is there any pack way?

**Comment by pencc** [comment]
@ArianK16a

**Comment by 1orz** [comment]
Encountered the same problem. How will the follow-up process be handled? Has it been resolved? @pencc

**Comment by ArianK16a** [comment]
This is meant to be used for AOSP.
Since the kernel uses modules, you don't just need the boot.img but vendor_boot, boot and vendor_dlkm
